chore: fix deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -32,8 +32,13 @@ jobs:
         id: find-apk
         shell: pwsh
         run: |
-          $apkPath = Get-ChildItem -Path . -Recurse -Filter "*.apk" | Select-Object -ExpandProperty FullName
-          echo "APK_PATH=$apkPath" | Out-File -FilePath $env:GITHUB_ENV -Append
+          $apkPath = Get-ChildItem -Path $Env:GITHUB_WORKSPACE -Recurse -Filter "*.apk" | Select-Object -ExpandProperty FullName
+          if ($apkPath) {
+            echo "APK_PATH=$apkPath" | Out-File -FilePath $env:GITHUB_ENV -Append
+          } else {
+            Write-Error "APK file not found!"
+            exit 1
+          }
 
       - name: Upload Unsigned APK
         uses: actions/upload-artifact@v4
